In [1]:
import pandas as pd
import numpy as np
import ast
import re
from datetime import datetime

In [2]:
df_main = pd.read_csv('steam_games.csv')
df_main.shape

C:\Users\joysa\AppData\Local\Temp\ipykernel_22860\3104821661.py:1: DtypeWarning: Columns (30,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df_main = pd.read_csv('steam_games.csv')

(136971, 42)

In [3]:
df = df_main.copy()

In [4]:
column_to_deleted = [
    'short_description', 'about_the_game', 'detailed_description', 
    'notes', 'header_image', 'screenshots', 'movies', 'website', 
    'support_url', 'support_email', 'metacritic_url', 
    'steam_store_available', 'steam_spy_available','packages'
]

df.drop(columns=column_to_deleted, inplace=True, errors='ignore')
df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,median_playtime_forever,average_playtime_2weeks,median_playtime_2weeks,achievements,dlc_count,supported_languages,full_audio_languages,windows,mac,linux
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"[""Alon Zubina""]","[""Alon Zubina""]","[""Adventure"", ""Indie"", ""Simulation""]","[""Single-player"", ""Family Sharing""]",...,325,0,0,0.0,0.0,"[""English""]","[""English""]",True,False,False
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"[""Orneon""]","[""BFG Entertainment""]","[""Adventure"", ""Casual""]","[""Single-player"", ""Family Sharing""]",...,0,0,0,0.0,0.0,"[""English""]","[""English""]",True,False,False
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"[""Media Impact Co.,Ltd""]","[""Media Impact Co.,Ltd""]","[""Free To Play"", ""RPG"", ""Early Access""]","[""Single-player""]",...,0,0,0,0.0,0.0,"[""English"", ""Japanese""]",[],True,False,False
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"[""BOHDOKUMEN.""]","[""BOHDOKUMEN.""]","[""Action"", ""Indie"", ""Strategy"", ""Early Access""]","[""Single-player"", ""Multi-player"", ""PvP"", ""Onli...",...,0,0,0,0.0,0.0,"[""English"", ""Simplified Chinese"", ""Traditional...",[],True,True,False
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"[""CRAFT""]","[""CRAFT""]","[""Indie"", ""Simulation"", ""Early Access""]","[""Single-player"", ""Steam Achievements"", ""Track...",...,0,0,0,5.0,0.0,"[""English""]","[""English""]",True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136966,554940,VR Apocalypse,2016-12-16,NaN,free,"0 .. 20,000","[""NextGen Games""]","[""NextGen Games""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,18.0,0.0,English<strong>*</strong><br><strong>*</strong...,NaN,True,False,False
136967,555810,Quicken WillMaker Plus 2017,2017-01-19,NaN,free,"50,000 .. 100,000","[""Nolo""]","[""Individual Software""]","[{""id"": ""50"", ""description"": ""Accounting""}]",[],...,0,0,0,NaN,0.0,English,NaN,True,True,False
136968,556750,SourVR Video Player,2016-11-21,0.00,free,"20,000 .. 50,000","[""River Twice Co., Ltd.""]","[""River Twice Co., Ltd.""]","[{""id"": ""57"", ""description"": ""Utilities""}]","[{""id"": 52, ""description"": ""Tracked Controller...",...,0,0,0,NaN,0.0,"English, Simplified Chinese, Traditional Chinese",NaN,True,False,False
136969,556820,Warbands: Bushido,2017-09-15,NaN,free,"100,000 .. 200,000","[""Red Unit Studios""]","[""Red Unit Studios""]","[{""id"": ""37"", ""description"": ""Free To Play""}, ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,28.0,0.0,"English, Russian, French, German, Spanish - Spain",NaN,True,True,True
136970,557180,League of Maidens®,2025-04-02,0.00,free,"500,000 .. 1,000,000","[""Maiden Gaming Inc.""]","[""Maiden Gaming Inc.""]","[{""id"": ""1"", ""description"": ""Action""}, {""id"": ...","[{""id"": 2, ""description"": ""Single-player""}, {""...",...,0,0,0,31.0,4.0,"English<strong>*</strong>, Japanese<strong>*</...",NaN,True,False,False

In [5]:
column_to_remove = ['genres', 'categories']

for col in column_to_remove:
    df[col] = df[col].str.replace(r'\{id:\s*\d+,\s*description:\s*', '', regex=True)
    df[col] = df[col].str.replace(r'\}', '', regex=True)
    df[col] = df[col].str.replace(r"['\"]", "", regex=True)

In [6]:
df['developers'] = df['developers'].str.replace(r'\[|\]', '', regex=True)
df['publishers'] = df['publishers'].str.replace(r'\[|\]', '', regex=True)
df['genres'] = df['genres'].str.replace(r'\[|\]', '', regex=True)
df['categories'] = df['categories'].str.replace(r'\[|\]', '', regex=True)

In [7]:
first_encoder = {True:1,False:0}
df['mac'] = df['mac'].map(first_encoder)
df['windows'] = df['windows'].map(first_encoder)
df['linux'] = df['linux'].map(first_encoder)

Null value handeling

As there are 17 Null value in name column,84 null value in release column and 84 price column  we should drop these value

In [8]:
df.dropna(subset=['name'], inplace=True)
df.dropna(subset=['release_date'], inplace=True)
df.dropna(subset=['price'], inplace=True)
df.dropna(subset=['supported_languages'],inplace=True)

as there are 19957 Null value in recommendations Column.But it may be true for the game that 0 people recommended these game so we shoud keep those null value and replace it by 0

In [9]:
df['recommendations'] = df['recommendations'].fillna(0)

As there  be 0 Metacritic Score so we should keep these value

In [10]:
df['metacritic_score'] = df['metacritic_score'].fillna(0)

It may be true to have Zero Achivement in the game so we are keeping these value

In [11]:
df['achievements'] = df['achievements'].fillna(0)

We should add none to all the missing value in the full audio language column

In [12]:
df['full_audio_languages'] = df['full_audio_languages'].fillna('None')

In [13]:
df.isnull().sum()

app_id                      0
name                        0
release_date                0
price                       0
price_status                0
estimated_owners            0
developers                  0
publishers                  0
genres                      0
categories                  0
tags                        0
positive                    0
negative                    0
recommendations             0
peak_ccu                    0
metacritic_score            0
user_score                  0
average_playtime_forever    0
median_playtime_forever     0
average_playtime_2weeks     0
median_playtime_2weeks      0
achievements                0
dlc_count                   0
supported_languages         0
full_audio_languages        0
windows                     0
mac                         0
linux                       0
dtype: int64

In [14]:
df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,median_playtime_forever,average_playtime_2weeks,median_playtime_2weeks,achievements,dlc_count,supported_languages,full_audio_languages,windows,mac,linux
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"""Alon Zubina""","""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,325,0,0,0.0,0.0,"[""English""]","[""English""]",1.0,0.0,0.0
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"""Orneon""","""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,0,0,0,0.0,0.0,"[""English""]","[""English""]",1.0,0.0,0.0
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"""Media Impact Co.,Ltd""","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,0,0,0,0.0,0.0,"[""English"", ""Japanese""]",[],1.0,0.0,0.0
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"""BOHDOKUMEN.""","""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,0,0,0,0.0,0.0,"[""English"", ""Simplified Chinese"", ""Traditional...",[],1.0,1.0,0.0
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"""CRAFT""","""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,0,0,0,5.0,0.0,"[""English""]","[""English""]",1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,"0 .. 20,000","""Cerevrum Inc.""","""Cerevrum Inc. ""","{id: 54, description: Education","{id: 52, description: Tracked Controller Suppo...",...,0,0,0,0.0,0.0,English<strong>*</strong><br><strong>*</strong...,None,1.0,0.0,0.0
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,"0 .. 20,000","""DatavizVR Inc.""","""DatavizVR Inc.""","{id: 50, description: Accounting, {id: 54, des...","{id: 52, description: Tracked Controller Suppo...",...,0,0,0,0.0,0.0,English<strong>*</strong><br><strong>*</strong...,None,1.0,0.0,0.0
136965,552770,Speech Trainer,2016-11-11,0.00,free,"0 .. 20,000","""Wolf In Motion Ltd""","""Wolf In Motion Ltd""","{id: 56, description: Software Training","{id: 52, description: Tracked Controller Suppo...",...,0,0,0,0.0,0.0,English,None,1.0,0.0,0.0
136968,556750,SourVR Video Player,2016-11-21,0.00,free,"20,000 .. 50,000","""River Twice Co., Ltd.""","""River Twice Co., Ltd.""","{id: 57, description: Utilities","{id: 52, description: Tracked Controller Suppo...",...,0,0,0,0.0,0.0,"English, Simplified Chinese, Traditional Chinese",None,1.0,0.0,0.0
136970,557180,League of Maidens®,2025-04-02,0.00,free,"500,000 .. 1,000,000","""Maiden Gaming Inc.""","""Maiden Gaming Inc.""","{id: 1, description: Action, {id: 25, descript...","{id: 2, description: Single-player, {id: 22, d...",...,0,0,0,31.0,4.0,"English<strong>*</strong>, Japanese<strong>*</...",None,1.0,0.0,0.0

Now we are creating two new column they lowest estimate owner and high estimate owner

In [15]:
df['estimated_owners'] = df['estimated_owners'].astype(str).str.replace(',', '', regex=False)
split_the_column = df['estimated_owners'].str.split(r'\s*(?:\.+|-+)\s*', expand=True)
df['lowest_estimate_owner'] = pd.to_numeric(split_the_column[0], errors='coerce')
df['highest_estimate_owner'] = pd.to_numeric(split_the_column[1], errors='coerce')
print(df[['lowest_estimate_owner', 'highest_estimate_owner']])

        lowest_estimate_owner  highest_estimate_owner
0                      200000                  500000
1                           0                   20000
2                           0                   20000
3                           0                   20000
4                           0                   20000
...                       ...                     ...
136963                      0                   20000
136964                      0                   20000
136965                      0                   20000
136968                  20000                   50000
136970                 500000                 1000000

[136108 rows x 2 columns]

In [16]:
df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,median_playtime_2weeks,achievements,dlc_count,supported_languages,full_audio_languages,windows,mac,linux,lowest_estimate_owner,highest_estimate_owner
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"""Alon Zubina""","""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,0,0.0,0.0,"[""English""]","[""English""]",1.0,0.0,0.0,200000,500000
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"""Orneon""","""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,0,0.0,0.0,"[""English""]","[""English""]",1.0,0.0,0.0,0,20000
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"""Media Impact Co.,Ltd""","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,0,0.0,0.0,"[""English"", ""Japanese""]",[],1.0,0.0,0.0,0,20000
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"""BOHDOKUMEN.""","""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,0,0.0,0.0,"[""English"", ""Simplified Chinese"", ""Traditional...",[],1.0,1.0,0.0,0,20000
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"""CRAFT""","""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,0,5.0,0.0,"[""English""]","[""English""]",1.0,0.0,0.0,0,20000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,"""Cerevrum Inc.""","""Cerevrum Inc. ""","{id: 54, description: Education","{id: 52, description: Tracked Controller Suppo...",...,0,0.0,0.0,English<strong>*</strong><br><strong>*</strong...,None,1.0,0.0,0.0,0,20000
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,"""DatavizVR Inc.""","""DatavizVR Inc.""","{id: 50, description: Accounting, {id: 54, des...","{id: 52, description: Tracked Controller Suppo...",...,0,0.0,0.0,English<strong>*</strong><br><strong>*</strong...,None,1.0,0.0,0.0,0,20000
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,"""Wolf In Motion Ltd""","""Wolf In Motion Ltd""","{id: 56, description: Software Training","{id: 52, description: Tracked Controller Suppo...",...,0,0.0,0.0,English,None,1.0,0.0,0.0,0,20000
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"""River Twice Co., Ltd.""","""River Twice Co., Ltd.""","{id: 57, description: Utilities","{id: 52, description: Tracked Controller Suppo...",...,0,0.0,0.0,"English, Simplified Chinese, Traditional Chinese",None,1.0,0.0,0.0,20000,50000
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,"""Maiden Gaming Inc.""","""Maiden Gaming Inc.""","{id: 1, description: Action, {id: 25, descript...","{id: 2, description: Single-player, {id: 22, d...",...,0,31.0,4.0,"English<strong>*</strong>, Japanese<strong>*</...",None,1.0,0.0,0.0,500000,1000000

we are creating more two column total revie and review score percentage and has review

In [17]:
df["positive"] = pd.to_numeric(df["positive"], errors="coerce").fillna(0)
df["negative"] = pd.to_numeric(df["negative"], errors="coerce").fillna(0)
df['total_review'] = df['positive']+df['negative']
df["review_score_pct"] = np.where(
        df["total_review"] > 0,
        df["positive"] / df["total_review"],
        np.nan,
    )
df["has_reviews"] = df["total_review"] > 0
df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,supported_languages,full_audio_languages,windows,mac,linux,lowest_estimate_owner,highest_estimate_owner,total_review,review_score_pct,has_reviews
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"""Alon Zubina""","""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,"[""English""]","[""English""]",1.0,0.0,0.0,200000,500000,289,0.788927,True
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"""Orneon""","""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,"[""English""]","[""English""]",1.0,0.0,0.0,0,20000,12,1.000000,True
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"""Media Impact Co.,Ltd""","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,"[""English"", ""Japanese""]",[],1.0,0.0,0.0,0,20000,22,0.727273,True
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"""BOHDOKUMEN.""","""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,"[""English"", ""Simplified Chinese"", ""Traditional...",[],1.0,1.0,0.0,0,20000,4,0.250000,True
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"""CRAFT""","""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,"[""English""]","[""English""]",1.0,0.0,0.0,0,20000,8,0.500000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,"""Cerevrum Inc.""","""Cerevrum Inc. ""","{id: 54, description: Education","{id: 52, description: Tracked Controller Suppo...",...,English<strong>*</strong><br><strong>*</strong...,None,1.0,0.0,0.0,0,20000,11,0.272727,True
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,"""DatavizVR Inc.""","""DatavizVR Inc.""","{id: 50, description: Accounting, {id: 54, des...","{id: 52, description: Tracked Controller Suppo...",...,English<strong>*</strong><br><strong>*</strong...,None,1.0,0.0,0.0,0,20000,21,0.904762,True
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,"""Wolf In Motion Ltd""","""Wolf In Motion Ltd""","{id: 56, description: Software Training","{id: 52, description: Tracked Controller Suppo...",...,English,None,1.0,0.0,0.0,0,20000,23,0.869565,True
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"""River Twice Co., Ltd.""","""River Twice Co., Ltd.""","{id: 57, description: Utilities","{id: 52, description: Tracked Controller Suppo...",...,"English, Simplified Chinese, Traditional Chinese",None,1.0,0.0,0.0,20000,50000,49,0.591837,True
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,"""Maiden Gaming Inc.""","""Maiden Gaming Inc.""","{id: 1, description: Action, {id: 25, descript...","{id: 2, description: Single-player, {id: 22, d...",...,"English<strong>*</strong>, Japanese<strong>*</...",None,1.0,0.0,0.0,500000,1000000,6017,0.544291,True

In [18]:
df['primary_genre'] = df['genres'].str.split(',').str[0]
df['genre_count'] = df['genres'].str.split(',').apply(len)
df['categories_count'] = df['categories'].str.split(',').apply(len)
df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,mac,linux,lowest_estimate_owner,highest_estimate_owner,total_review,review_score_pct,has_reviews,primary_genre,genre_count,categories_count
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"""Alon Zubina""","""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,0.0,0.0,200000,500000,289,0.788927,True,Adventure,3,2
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"""Orneon""","""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,0.0,0.0,0,20000,12,1.000000,True,Adventure,2,2
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"""Media Impact Co.,Ltd""","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,0.0,0.0,0,20000,22,0.727273,True,Free To Play,3,1
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"""BOHDOKUMEN.""","""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,1.0,0.0,0,20000,4,0.250000,True,Action,4,7
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"""CRAFT""","""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,0.0,0.0,0,20000,8,0.500000,True,Indie,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,"""Cerevrum Inc.""","""Cerevrum Inc. ""","{id: 54, description: Education","{id: 52, description: Tracked Controller Suppo...",...,0.0,0.0,0,20000,11,0.272727,True,{id: 54,2,6
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,"""DatavizVR Inc.""","""DatavizVR Inc.""","{id: 50, description: Accounting, {id: 54, des...","{id: 52, description: Tracked Controller Suppo...",...,0.0,0.0,0,20000,21,0.904762,True,{id: 50,10,6
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,"""Wolf In Motion Ltd""","""Wolf In Motion Ltd""","{id: 56, description: Software Training","{id: 52, description: Tracked Controller Suppo...",...,0.0,0.0,0,20000,23,0.869565,True,{id: 56,2,4
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"""River Twice Co., Ltd.""","""River Twice Co., Ltd.""","{id: 57, description: Utilities","{id: 52, description: Tracked Controller Suppo...",...,0.0,0.0,20000,50000,49,0.591837,True,{id: 57,2,4
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,"""Maiden Gaming Inc.""","""Maiden Gaming Inc.""","{id: 1, description: Action, {id: 25, descript...","{id: 2, description: Single-player, {id: 22, d...",...,0.0,0.0,500000,1000000,6017,0.544291,True,{id: 1,14,10

In [19]:
df['patforms_count'] = df[['mac', 'windows', 'linux']].sum(axis=1)

In [20]:
df['languages_count'] = df['supported_languages'].str.split(',').apply(len)
df['primary_language'] = df['supported_languages'].str.split(',').str[0]

df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,highest_estimate_owner,total_review,review_score_pct,has_reviews,primary_genre,genre_count,categories_count,patforms_count,languages_count,primary_language
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"""Alon Zubina""","""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,500000,289,0.788927,True,Adventure,3,2,1.0,1,"[""English""]"
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"""Orneon""","""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,20000,12,1.000000,True,Adventure,2,2,1.0,1,"[""English""]"
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"""Media Impact Co.,Ltd""","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,20000,22,0.727273,True,Free To Play,3,1,1.0,2,"[""English"""
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"""BOHDOKUMEN.""","""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,20000,4,0.250000,True,Action,4,7,2.0,5,"[""English"""
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"""CRAFT""","""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,20000,8,0.500000,True,Indie,3,6,1.0,1,"[""English""]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,"""Cerevrum Inc.""","""Cerevrum Inc. ""","{id: 54, description: Education","{id: 52, description: Tracked Controller Suppo...",...,20000,11,0.272727,True,{id: 54,2,6,1.0,1,English<strong>*</strong><br><strong>*</strong...
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,"""DatavizVR Inc.""","""DatavizVR Inc.""","{id: 50, description: Accounting, {id: 54, des...","{id: 52, description: Tracked Controller Suppo...",...,20000,21,0.904762,True,{id: 50,10,6,1.0,1,English<strong>*</strong><br><strong>*</strong...
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,"""Wolf In Motion Ltd""","""Wolf In Motion Ltd""","{id: 56, description: Software Training","{id: 52, description: Tracked Controller Suppo...",...,20000,23,0.869565,True,{id: 56,2,4,1.0,1,English
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"""River Twice Co., Ltd.""","""River Twice Co., Ltd.""","{id: 57, description: Utilities","{id: 52, description: Tracked Controller Suppo...",...,50000,49,0.591837,True,{id: 57,2,4,1.0,3,English
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,"""Maiden Gaming Inc.""","""Maiden Gaming Inc.""","{id: 1, description: Action, {id: 25, descript...","{id: 2, description: Single-player, {id: 22, d...",...,1000000,6017,0.544291,True,{id: 1,14,10,1.0,4,English<strong>*</strong>

In [21]:
df['age_by_years'] = (datetime.now() - pd.to_datetime(df['release_date'], errors='coerce')).dt.days / 365.25
df['release_quarter'] = pd.to_datetime(df['release_date'], errors='coerce').dt.quarter

df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,review_score_pct,has_reviews,primary_genre,genre_count,categories_count,patforms_count,languages_count,primary_language,age_by_years,release_quarter
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"""Alon Zubina""","""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,0.788927,True,Adventure,3,2,1.0,1,"[""English""]",9.705681,4
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"""Orneon""","""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,1.000000,True,Adventure,2,2,1.0,1,"[""English""]",9.708419,4
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"""Media Impact Co.,Ltd""","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,0.727273,True,Free To Play,3,1,1.0,2,"[""English""",9.620808,4
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"""BOHDOKUMEN.""","""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,0.250000,True,Action,4,7,2.0,5,"[""English""",9.149897,2
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"""CRAFT""","""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,0.500000,True,Indie,3,6,1.0,1,"[""English""]",9.664613,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,"""Cerevrum Inc.""","""Cerevrum Inc. ""","{id: 54, description: Education","{id: 52, description: Tracked Controller Suppo...",...,0.272727,True,{id: 54,2,6,1.0,1,English<strong>*</strong><br><strong>*</strong...,9.566051,1
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,"""DatavizVR Inc.""","""DatavizVR Inc.""","{id: 50, description: Accounting, {id: 54, des...","{id: 52, description: Tracked Controller Suppo...",...,0.904762,True,{id: 50,10,6,1.0,1,English<strong>*</strong><br><strong>*</strong...,9.670089,4
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,"""Wolf In Motion Ltd""","""Wolf In Motion Ltd""","{id: 56, description: Software Training","{id: 52, description: Tracked Controller Suppo...",...,0.869565,True,{id: 56,2,4,1.0,1,English,9.735797,4
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"""River Twice Co., Ltd.""","""River Twice Co., Ltd.""","{id: 57, description: Utilities","{id: 52, description: Tracked Controller Suppo...",...,0.591837,True,{id: 57,2,4,1.0,3,English,9.708419,4
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,"""Maiden Gaming Inc.""","""Maiden Gaming Inc.""","{id: 1, description: Action, {id: 25, descript...","{id: 2, description: Single-player, {id: 22, d...",...,0.544291,True,{id: 1,14,10,1.0,4,English<strong>*</strong>,1.347023,2

In [22]:
df['has_achievements'] = df['achievements'] > 0
df['achievements_count'] = df['achievements'].apply(lambda x: len(ast.literal_eval(x)) if isinstance(x, str) else 0)
df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,primary_genre,genre_count,categories_count,patforms_count,languages_count,primary_language,age_by_years,release_quarter,has_achievements,achievements_count
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"""Alon Zubina""","""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,Adventure,3,2,1.0,1,"[""English""]",9.705681,4,False,0
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"""Orneon""","""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,Adventure,2,2,1.0,1,"[""English""]",9.708419,4,False,0
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"""Media Impact Co.,Ltd""","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,Free To Play,3,1,1.0,2,"[""English""",9.620808,4,False,0
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"""BOHDOKUMEN.""","""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,Action,4,7,2.0,5,"[""English""",9.149897,2,False,0
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"""CRAFT""","""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,Indie,3,6,1.0,1,"[""English""]",9.664613,4,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,"""Cerevrum Inc.""","""Cerevrum Inc. ""","{id: 54, description: Education","{id: 52, description: Tracked Controller Suppo...",...,{id: 54,2,6,1.0,1,English<strong>*</strong><br><strong>*</strong...,9.566051,1,False,0
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,"""DatavizVR Inc.""","""DatavizVR Inc.""","{id: 50, description: Accounting, {id: 54, des...","{id: 52, description: Tracked Controller Suppo...",...,{id: 50,10,6,1.0,1,English<strong>*</strong><br><strong>*</strong...,9.670089,4,False,0
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,"""Wolf In Motion Ltd""","""Wolf In Motion Ltd""","{id: 56, description: Software Training","{id: 52, description: Tracked Controller Suppo...",...,{id: 56,2,4,1.0,1,English,9.735797,4,False,0
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"""River Twice Co., Ltd.""","""River Twice Co., Ltd.""","{id: 57, description: Utilities","{id: 52, description: Tracked Controller Suppo...",...,{id: 57,2,4,1.0,3,English,9.708419,4,False,0
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,"""Maiden Gaming Inc.""","""Maiden Gaming Inc.""","{id: 1, description: Action, {id: 25, descript...","{id: 2, description: Single-player, {id: 22, d...",...,{id: 1,14,10,1.0,4,English<strong>*</strong>,1.347023,2,True,0

In [23]:
df['price_tier'] = pd.cut(df['price'], bins=[-1, 0, 10, 30, 60, np.inf], labels=['Free', 'Budget', 'Mid-range', 'Premium', 'AAA'])
df


df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,genre_count,categories_count,patforms_count,languages_count,primary_language,age_by_years,release_quarter,has_achievements,achievements_count,price_tier
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"""Alon Zubina""","""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,3,2,1.0,1,"[""English""]",9.705681,4,False,0,Budget
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"""Orneon""","""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,2,2,1.0,1,"[""English""]",9.708419,4,False,0,Mid-range
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"""Media Impact Co.,Ltd""","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,3,1,1.0,2,"[""English""",9.620808,4,False,0,Free
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"""BOHDOKUMEN.""","""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,4,7,2.0,5,"[""English""",9.149897,2,False,0,Mid-range
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"""CRAFT""","""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,3,6,1.0,1,"[""English""]",9.664613,4,True,0,Budget
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,"""Cerevrum Inc.""","""Cerevrum Inc. ""","{id: 54, description: Education","{id: 52, description: Tracked Controller Suppo...",...,2,6,1.0,1,English<strong>*</strong><br><strong>*</strong...,9.566051,1,False,0,Budget
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,"""DatavizVR Inc.""","""DatavizVR Inc.""","{id: 50, description: Accounting, {id: 54, des...","{id: 52, description: Tracked Controller Suppo...",...,10,6,1.0,1,English<strong>*</strong><br><strong>*</strong...,9.670089,4,False,0,Free
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,"""Wolf In Motion Ltd""","""Wolf In Motion Ltd""","{id: 56, description: Software Training","{id: 52, description: Tracked Controller Suppo...",...,2,4,1.0,1,English,9.735797,4,False,0,Free
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"""River Twice Co., Ltd.""","""River Twice Co., Ltd.""","{id: 57, description: Utilities","{id: 52, description: Tracked Controller Suppo...",...,2,4,1.0,3,English,9.708419,4,False,0,Free
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,"""Maiden Gaming Inc.""","""Maiden Gaming Inc.""","{id: 1, description: Action, {id: 25, descript...","{id: 2, description: Single-player, {id: 22, d...",...,14,10,1.0,4,English<strong>*</strong>,1.347023,2,True,0,Free

In [24]:
df['playtime_engagment_ration'] = df['average_playtime_forever'] / df['median_playtime_forever']+1
df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,categories_count,patforms_count,languages_count,primary_language,age_by_years,release_quarter,has_achievements,achievements_count,price_tier,playtime_engagment_ration
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"""Alon Zubina""","""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,2,1.0,1,"[""English""]",9.705681,4,False,0,Budget,1.815385
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"""Orneon""","""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,2,1.0,1,"[""English""]",9.708419,4,False,0,Mid-range,NaN
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"""Media Impact Co.,Ltd""","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,1,1.0,2,"[""English""",9.620808,4,False,0,Free,NaN
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"""BOHDOKUMEN.""","""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,7,2.0,5,"[""English""",9.149897,2,False,0,Mid-range,NaN
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"""CRAFT""","""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,6,1.0,1,"[""English""]",9.664613,4,True,0,Budget,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,"""Cerevrum Inc.""","""Cerevrum Inc. ""","{id: 54, description: Education","{id: 52, description: Tracked Controller Suppo...",...,6,1.0,1,English<strong>*</strong><br><strong>*</strong...,9.566051,1,False,0,Budget,NaN
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,"""DatavizVR Inc.""","""DatavizVR Inc.""","{id: 50, description: Accounting, {id: 54, des...","{id: 52, description: Tracked Controller Suppo...",...,6,1.0,1,English<strong>*</strong><br><strong>*</strong...,9.670089,4,False,0,Free,NaN
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,"""Wolf In Motion Ltd""","""Wolf In Motion Ltd""","{id: 56, description: Software Training","{id: 52, description: Tracked Controller Suppo...",...,4,1.0,1,English,9.735797,4,False,0,Free,NaN
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"""River Twice Co., Ltd.""","""River Twice Co., Ltd.""","{id: 57, description: Utilities","{id: 52, description: Tracked Controller Suppo...",...,4,1.0,3,English,9.708419,4,False,0,Free,NaN
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,"""Maiden Gaming Inc.""","""Maiden Gaming Inc.""","{id: 1, description: Action, {id: 25, descript...","{id: 2, description: Single-player, {id: 22, d...",...,10,1.0,4,English<strong>*</strong>,1.347023,2,True,0,Free,NaN

In [25]:
df['playtime_engagment_ratio'] = df['playtime_engagment_ration'].fillna(0)

In [26]:
df['recent_vs_lifetime_engagment'] = df['average_playtime_2weeks']/df['average_playtime_forever']+1
df['value_score'] = df['metacritic_score'] / df['price']

In [27]:
df['developers'] = df['developers'].str.replace(r'\[\]\"', '', regex=True)

In [28]:
df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,primary_language,age_by_years,release_quarter,has_achievements,achievements_count,price_tier,playtime_engagment_ration,playtime_engagment_ratio,recent_vs_lifetime_engagment,value_score
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,"""Alon Zubina""","""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,"[""English""]",9.705681,4,False,0,Budget,1.815385,1.815385,1.0,0.0
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,"""Orneon""","""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,"[""English""]",9.708419,4,False,0,Mid-range,NaN,0.000000,NaN,0.0
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"""Media Impact Co.,Ltd""","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,"[""English""",9.620808,4,False,0,Free,NaN,0.000000,NaN,NaN
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,"""BOHDOKUMEN.""","""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,"[""English""",9.149897,2,False,0,Mid-range,NaN,0.000000,NaN,0.0
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,"""CRAFT""","""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,"[""English""]",9.664613,4,True,0,Budget,NaN,0.000000,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,"""Cerevrum Inc.""","""Cerevrum Inc. ""","{id: 54, description: Education","{id: 52, description: Tracked Controller Suppo...",...,English<strong>*</strong><br><strong>*</strong...,9.566051,1,False,0,Budget,NaN,0.000000,NaN,0.0
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,"""DatavizVR Inc.""","""DatavizVR Inc.""","{id: 50, description: Accounting, {id: 54, des...","{id: 52, description: Tracked Controller Suppo...",...,English<strong>*</strong><br><strong>*</strong...,9.670089,4,False,0,Free,NaN,0.000000,NaN,NaN
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,"""Wolf In Motion Ltd""","""Wolf In Motion Ltd""","{id: 56, description: Software Training","{id: 52, description: Tracked Controller Suppo...",...,English,9.735797,4,False,0,Free,NaN,0.000000,NaN,NaN
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"""River Twice Co., Ltd.""","""River Twice Co., Ltd.""","{id: 57, description: Utilities","{id: 52, description: Tracked Controller Suppo...",...,English,9.708419,4,False,0,Free,NaN,0.000000,NaN,NaN
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,"""Maiden Gaming Inc.""","""Maiden Gaming Inc.""","{id: 1, description: Action, {id: 25, descript...","{id: 2, description: Single-player, {id: 22, d...",...,English<strong>*</strong>,1.347023,2,True,0,Free,NaN,0.000000,NaN,NaN

In [29]:
df['categories'] = df['categories'].str.replace(r'\{id:\s*\d+,\s*description:\s*', '', regex=True)
df['genres'] = df['genres'].str.replace(r'\{id:\s*\d+,\s*description:\s*', '', regex=True)
df['has_english'] = df['supported_languages'].str.contains('English', case=False, na=False).astype(int)

In [31]:
df['developers'] = df['developers'].str.replace(r'\"', '', regex=True)

In [32]:
df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,age_by_years,release_quarter,has_achievements,achievements_count,price_tier,playtime_engagment_ration,playtime_engagment_ratio,recent_vs_lifetime_engagment,value_score,has_english
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,Alon Zubina,"""Alon Zubina""","Adventure, Indie, Simulation","Single-player, Family Sharing",...,9.705681,4,False,0,Budget,1.815385,1.815385,1.0,0.0,1
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,Orneon,"""BFG Entertainment""","Adventure, Casual","Single-player, Family Sharing",...,9.708419,4,False,0,Mid-range,NaN,0.000000,NaN,0.0,1
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"Media Impact Co.,Ltd","""Media Impact Co.,Ltd""","Free To Play, RPG, Early Access",Single-player,...,9.620808,4,False,0,Free,NaN,0.000000,NaN,NaN,1
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,BOHDOKUMEN.,"""BOHDOKUMEN.""","Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,9.149897,2,False,0,Mid-range,NaN,0.000000,NaN,0.0,1
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,CRAFT,"""CRAFT""","Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,9.664613,4,True,0,Budget,NaN,0.000000,NaN,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,Cerevrum Inc.,"""Cerevrum Inc. """,Education,"Tracked Controller Support, VR Only, Steam Wor...",...,9.566051,1,False,0,Budget,NaN,0.000000,NaN,0.0,1
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,DatavizVR Inc.,"""DatavizVR Inc.""","Accounting, Education, Software Training, Util...","Tracked Controller Support, VR Only, Stats",...,9.670089,4,False,0,Free,NaN,0.000000,NaN,NaN,1
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,Wolf In Motion Ltd,"""Wolf In Motion Ltd""",Software Training,"Tracked Controller Support, VR Only",...,9.735797,4,False,0,Free,NaN,0.000000,NaN,NaN,1
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"River Twice Co., Ltd.","""River Twice Co., Ltd.""",Utilities,"Tracked Controller Support, VR Supported",...,9.708419,4,False,0,Free,NaN,0.000000,NaN,NaN,1
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,Maiden Gaming Inc.,"""Maiden Gaming Inc.""","Action, Adventure, Casual, Indie, RPG, Strateg...","Single-player, Steam Achievements, In-App Purc...",...,1.347023,2,True,0,Free,NaN,0.000000,NaN,NaN,1

In [33]:
df['publishers'] = df['publishers'].str.replace(r'\"', '', regex=True)

In [34]:
df

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,age_by_years,release_quarter,has_achievements,achievements_count,price_tier,playtime_engagment_ration,playtime_engagment_ratio,recent_vs_lifetime_engagment,value_score,has_english
0,558660,it's always monday,2016-11-22,1.99,paid,200000 - 500000,Alon Zubina,Alon Zubina,"Adventure, Indie, Simulation","Single-player, Family Sharing",...,9.705681,4,False,0,Budget,1.815385,1.815385,1.0,0.0,1
1,558670,The Agency of Anomalies: Cinderstone Orphanage...,2016-11-21,19.99,paid,0 - 20000,Orneon,BFG Entertainment,"Adventure, Casual","Single-player, Family Sharing",...,9.708419,4,False,0,Mid-range,NaN,0.000000,NaN,0.0,1
2,558680,KYOTO TANOJI QUEST,2016-12-23,0.00,free,0 - 20000,"Media Impact Co.,Ltd","Media Impact Co.,Ltd","Free To Play, RPG, Early Access",Single-player,...,9.620808,4,False,0,Free,NaN,0.000000,NaN,NaN,1
3,558720,Tribal Siege,2017-06-13,19.99,paid,0 - 20000,BOHDOKUMEN.,BOHDOKUMEN.,"Action, Indie, Strategy, Early Access","Single-player, Multi-player, PvP, Online PvP, ...",...,9.149897,2,False,0,Mid-range,NaN,0.000000,NaN,0.0,1
4,558740,CRAFT: Work VR Shop,2016-12-07,6.99,paid,0 - 20000,CRAFT,CRAFT,"Indie, Simulation, Early Access","Single-player, Steam Achievements, Tracked Con...",...,9.664613,4,True,0,Budget,NaN,0.000000,NaN,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136963,551780,Dating Lessons,2017-01-12,9.99,paid,0 .. 20000,Cerevrum Inc.,Cerevrum Inc.,Education,"Tracked Controller Support, VR Only, Steam Wor...",...,9.566051,1,False,0,Budget,NaN,0.000000,NaN,0.0,1
136964,551960,DatavizVR Demo,2016-12-05,0.00,free,0 .. 20000,DatavizVR Inc.,DatavizVR Inc.,"Accounting, Education, Software Training, Util...","Tracked Controller Support, VR Only, Stats",...,9.670089,4,False,0,Free,NaN,0.000000,NaN,NaN,1
136965,552770,Speech Trainer,2016-11-11,0.00,free,0 .. 20000,Wolf In Motion Ltd,Wolf In Motion Ltd,Software Training,"Tracked Controller Support, VR Only",...,9.735797,4,False,0,Free,NaN,0.000000,NaN,NaN,1
136968,556750,SourVR Video Player,2016-11-21,0.00,free,20000 .. 50000,"River Twice Co., Ltd.","River Twice Co., Ltd.",Utilities,"Tracked Controller Support, VR Supported",...,9.708419,4,False,0,Free,NaN,0.000000,NaN,NaN,1
136970,557180,League of Maidens®,2025-04-02,0.00,free,500000 .. 1000000,Maiden Gaming Inc.,Maiden Gaming Inc.,"Action, Adventure, Casual, Indie, RPG, Strateg...","Single-player, Steam Achievements, In-App Purc...",...,1.347023,2,True,0,Free,NaN,0.000000,NaN,NaN,1

np.int64(0)